### ISSUE TITLE
Cannot build reader-soup on GHC 8.10

### ISSUE THREAD

**Issue by ocharles** [tweag/porcupine#82]
**Describe the bug**

I cannot build `reader-soup` on GHC 8.10.

**To Reproduce**

`cabal build reader-soup` on GHC 8.10.

**Expected behavior**

It builds

**Additional context**

The failure is:

```
[1 of 4] Compiling Control.Monad.ReaderSoup ( src/Control/Monad/ReaderSoup.hs, dist/build/Control/Monad/ReaderSoup.o, dist/build/Control/Monad/ReaderSoup.dyn_o )

src/Control/Monad/ReaderSoup.hs:127:17: error:
    • Expected kind ‘(k -> *) -> [k] -> *’,
        but ‘r’ has kind ‘((Symbol, *) -> *) -> [(Symbol, *)] -> *’
    • In the first argument of ‘RecElemFCtx’, namely ‘r’
      In the type ‘(HasField r l ctxs ctxs (ContextFromName l) (ContextFromName l),
                    RecElemFCtx r ElField)’
      In the type declaration for ‘IsInSoup_’
    |
127 |   , RecElemFCtx r ElField )
```

Perhaps this is a problem with `vinyl`, which does at least build on 8.10, but may have things incorrectly typed?

**Comment by ocharles** [comment]
I tried enabling `PolyKinds` but the problem remains, so it's not that.

**Comment by YPares** [comment]
Hello! Yes I think it came from vinyl's version. Latest version I believe doesn't have this problem.
This has been fixed on our internal dev branch, which I should port back to this repository soon.

**Comment by ocharles** [comment]
Oh yes, the associated issue above is me fixing the problem in vinyl. reader-soup does build with the fix!
